### Finds all users in the system
GET http://localhost:8080/api/info/all
Accept: application/json

### Finds a user by id
GET http://localhost:8080/api/info/user/1
Accept: application/json

###
POST http://localhost:8080/api/info/
Content-Type: application/json

{"userName": "oscar10", "userPass": "test", "roles": []}

###
PUT http://localhost:8080/api/info/user/update
Content-Type: application/json

{"id":3,"userName": "oscar6", "userPass": "test", "roles": ["user"]}

### Deletes a user by id
DELETE http://localhost:8080/api/info/user/18
Accept: application/json

###
POST https://tuff.systems/BackEnd_CA2/api/info
Content-Type: application/json

{"userName": "testadmin", "userPass": "test", "roles": ["user","admin"]}

###
POST https://tuff.systems/BackEnd_CA2/api/login
Content-Type: application/json

{"username": "oscar", "password": "test"}

###
POST http://localhost:8080/api/login
Content-Type: application/json

{"username": "oscar", "password": "test"}
